In [8]:
#Creating an array in numpy
import numpy as np
arr = np.array([1,2,3,4,5]) #creating array using array() and np for ndarray
print(arr)

[1 2 3 4 5]


In [9]:
#0-D arrays
import numpy as np
arr = np.array(42) # only 1 argument without any [] so 0-D
print(arr)

42


In [10]:
#1-D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
#2-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#highrer dimension array
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
